apiVersion: v2
name: hashicorp-vault
description: A Helm chart for Kubernetes

type: application

version: 0.0.1

appVersion: "0.0.1"

dependencies:
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.30.1