vault:
  server:
    updateStrategyType: "OnDelete"
    statefulSet:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
    ingress:
      enabled: true
      ingressClassName: nginx
      labels:
        app: hashicorp-vault
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: vault.workquark.org
        external-dns.alpha.kubernetes.io/target: 96d9d557-1bc6-4572-a608-a6330e6b5f90.cfargotunnel.com
      hosts:
      - host: vault.192.168.49.100.nip.io
        paths: [ / ]
      - host: vault.workquark.org
        paths: [ / ]
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local
    dataStorage:
      enabled: true
      size: 10Gi
      storageClass: openebs-hostpath
      accessMode: ReadWriteOnce
