vault:
  server:
    ha:
      enabled: true
      replicas: 1
    dataStorage:
      enabled: true
      storageClass: standard
    haStorage:
      raft:
        enabled: true
    standalone:
      enabled: false

  injector:
    enabled: false

  ui:
    enabled: true
