apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: "my-ca"
  secretName: ca-key-pair
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
