apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit-nginx-logs
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: fluentbit-nginx-logs
  template:
    metadata:
      labels:
        app: fluentbit-nginx-logs
    spec:
      containers:
        - name: fluentbit
          image: fluent/fluent-bit:1.8
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: fluentbit-config
              mountPath: /fluent-bit/etc
              subPath: fluent-bit.conf
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: fluentbit-config
          configMap:
            name: fluentbit-config
            