ingress-nginx:
  controller:
    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: monitoring

    admissionWebhooks:
      enabled: false