apiVersion: operator.victoriametrics.com/v1
kind: VLCluster
metadata:
  name: victoria-metrics-cluster
spec:
  vlinsert:
    replicaCount: 2
  vlselect:
    replicaCount: 2
  vlstorage:
    retentionPeriod: "1y"
    replicaCount: 2
  requestsLoadBalancer:
    enabled: true
    spec:
     replicaCount: 2