apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            environment: default
  template:
    metadata:
      name: "{{`{{cluster}}`}}-kube-prometheus-stack"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:defyjoy/kubernetes-monitoring.git
        targetRevision: feat/argocd-deployment
        path: apps/kube-prometheus-stack
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: "{{`{{url}}`}}"
        namespace: kube-prometheus-stack
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
          namespace: kube-prometheus-stack
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /metadata/annotations
          namespace: kube-prometheus-stack
        # - group: monitoring.coreos.com
        #   kind: ServiceMonitor
        #   jsonPointers:
        #     - /metadata/annotations
        #   namespace: kube-prometheus-stack
        # - group: monitoring.coreos.com
        #   kind: PrometheusRule
        #   jsonPointers:
        #     - /metadata/annotations
