apiVersion: v2
name: victoria-metrics-operator
description: A Helm chart for Kubernetes

type: application

version: 0.0.1

appVersion: "0.0.1"

dependencies:
- name: victoria-metrics-operator
  repository: https://victoriametrics.github.io/helm-charts/
  version: 0.51.2
