apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: victoria-auth
spec:
  replicaCount: 1
  selectAllByDefault: true
  ingress:
    name: victoria-auth-ingress
    class_name: nginx
    host: 172.18.0.0.nip.io
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 100M
#   # unauthorizedUserAccessSpec:
#   #   - src_paths: ["/metrics"]
#   #     # url_prefix:
#   #     #   - http://vmsingle-example.default.svc:8428
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser
spec:
  username: admin
  password: password
  targetRefs:
  - static:
      url: http://vlinsert-example.default.svc:9481
    paths: ["/"]
  # - crd:
  #     kind: VMAgent
  #     name: sample
  #     namespace: default
  #   paths: ["/targets", "/api/v1/targets", "/api/v1/write"]