vector:
  role: "Agent" # Other options: "Aggregator"

  # Vector agent configuration
  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
    transforms:
      transform-kubelogs:
        inputs:
        - kubernetes_logs
        type: remap
        source: |
          del(.kubernetes.pod_labels)
          ._msg = .message
          # .formatted_message = parse_json!(.message)  
    sinks:
      victorialogs:
        type: loki
        inputs:
        - transform-kubelogs
        # endpoint: http://vmauth.172.18.0.0.nip.io/insert # victoria logs loki format
        endpoint: http://vmauth.workquark.org/insert # victoria logs loki format/ via cloudflare tunnel
        encoding:
          codec: json
        labels:
          job: vector
          namespace: "{{`{{ kubernetes.pod_namespace }}`}}"
          container: "{{`{{ kubernetes.container_name }}`}}"
        healthcheck: false
        request:
          in_flight_limit: 1
        out_of_order_action: accept
        path: /loki/api/v1/push
        remove_timestamp: true
        auth:
          strategy: basic
          user: writer
          password: password
      grafana-loki:
        type: loki
        tenant_id: dev
        inputs:
        - transform-kubelogs
        # endpoint: http://172.18.0.0.nip.io/insert # victoria logs loki format
        endpoint: http://loki-gateway.172.18.0.0.nip.io
        encoding:
          codec: json
        labels:
          job: vector
          namespace: "{{`{{ kubernetes.pod_namespace }}`}}"
          container: "{{`{{ kubernetes.container_name }}`}}"
        healthcheck: false
        request:
          in_flight_limit: 1
        out_of_order_action: accept
        path: /loki/api/v1/push
        remove_timestamp: true
        auth:
          strategy: basic
          user: loki
          password: password
  serviceAccount:
    create: true
    name: ""

  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

  nodeSelector: {}

  affinity: {}

  service:
    enabled: false
