
cloudflared:

  # -- Please find more configuration from https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments/
  tunnelConfig:
    # -- cloudflared tunnel name
    name: "BEELINK-TUNNEL"
    metricsUpdateFrequency: 5s
    autoUpdateFrequency: 24h
    noAutoUpdate: true
    gracePeriod: 30s
    retries: 5
    # auto, http2, h2mux, quic
    protocol: auto
    # info, warn, error, fatal, panic
    logLevel: info
    transportLogLevel: warn
    connectTimeout: 30s
    warpRouting: false

  # -- Cloudflare ingress rules. More information can be found here: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/configuration-file/#how-traffic-is-matched
  ingress:
    - hostname: "*.workquark.org" # or "*.example.com" but you must define a CNAME record for "*" to your DNS
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      originRequest:
        noTlsVerify: true

    - service: http_status:404
