apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: admin
  labels:
    auth: "true"
spec:
  username: admin
  password: password
  targetRefs:
    # - crd:
    #     kind: VMSingle
    #     name: example
    #     namespace: default
    #   paths: ["/.*"]
    - static:
        url: http://vlclusterlb-victoria-metrics-cluster.victoria-metrics-operator.svc:8427
      paths: 
        - /